### ISSUE TITLE
Cannot run because go-xorm/core is gone

### ISSUE THREAD

**Issue by movsb** [volatiletech/boilbench#2]
It reports `mimic` is unknown.

```
boilbench (master) → go test -bench . -benchmem
`mimic` is not officially supported, running under compatibility mode.
goos: darwin
goarch: amd64
pkg: github.com/volatiletech/boilbench
BenchmarkGORMDelete/gorm-8       	  200000	     10849 ns/op	    4666 B/op	      95 allocs/op
BenchmarkGORPDelete/gorp-8       	 1000000	      1404 ns/op	     352 B/op	      13 allocs/op
panic: Unsupported driver name: mimic

goroutine 8 [running]:
github.com/volatiletech/boilbench.BenchmarkXORMDelete(0xc00022c4e0)
	/Users/tao.yang/codes/gocodes/src/github.com/volatiletech/boilbench/delete_test.go:85 +0x296
testing.(*B).runN(0xc00022c4e0, 0x1)
	/usr/local/go/src/testing/benchmark.go:176 +0xb3
testing.(*B).run1.func1(0xc00022c4e0)
	/usr/local/go/src/testing/benchmark.go:249 +0x5a
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:242 +0x7d
exit status 2
FAIL	github.com/volatiletech/boilbench	3.727s
```

I don't know if it's the reason below:

Xorm has transferred from GitHub to GiTea. 

Your mimic driver imports [github.com/go-xorm/core](https://github.com/volatiletech/boilbench/blob/08cf9b64d109068f4622863e8de0812fb0a8f4f7/mimic/mimic.go#L10) but the xorm itself imports [xorm.io/core](https://github.com/go-xorm/xorm/blame/f3e6c3a26b8f7e70fee2751b885531c81bdfa928/xorm.go#L18).

Maybe you should enable go mod for boilbench.

**Comment by aarondl** [comment]
Pushed fixes for this. Seems to run again. xorm.io is actually reachable and provides packages. Go modules would not have helped here and it's more effort than this repository is worth :)
